version: '3.8'

services:
  mongodb:
    image: mongo:latest
    #    container_name: mongo
    ports:
      - "6002:27017"  # 将MongoDB的27017端口映射到主机上的27017端口
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # 设置MongoDB的管理员用户名
      MONGO_INITDB_ROOT_PASSWORD: password  # 设置MongoDB的管理员密码
    volumes:
      - mongo_data:/data/db  # 创建一个卷并挂载到MongoDB的数据目录
volumes:
  mongo_data:  # 定义名为mongo-data的卷